### ISSUE TITLE
Rviz Plugin Just Displays Status as CAN, cannot reset or enable, status will not change

### ISSUE THREAD

**Issue by kuobenj** [CPR-Robots/cpr_mover#2]
![screenshot from 2016-10-27 17 21 10](https://cloud.githubusercontent.com/assets/9329463/19785999/cf4fd194-9c69-11e6-9c39-332ce6202d59.png)

**Comment by CPR-Robots** [comment]
Hi Kuobenj,

at first please try with our Windows software CPRog if you can connect and move the robot. This ensures that it is not a hardware problem. If you do get problems here please see hints at our Wiki:
http://wiki.cpr-robots.com/index.php?title=Troubleshooting
If this does not help please send me a mail at crm@cpr-robots.com with some more details.

If the robot works with CPRog please restart the complete ROS environment and check if the RVizPlugin is loaded twice.

Hope this helps, best regards, Christian

**Comment by kuobenj** [comment]
I don't remember how the problem was resolved
